/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiveOverlayIdRouteImport } from './routes/live.$overlayId'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as LiveOverlayIdPreviewRouteImport } from './routes/live.$overlayId.preview'
import { Route as LiveOverlayIdMetricsRouteImport } from './routes/live.$overlayId.metrics'
import { Route as LiveOverlayIdMapRouteImport } from './routes/live.$overlayId.map'
import { Route as LiveOverlayIdMetricMetricRouteImport } from './routes/live.$overlayId.metric.$metric'
import { Route as ApiLiveOverlayIdSessionRouteImport } from './routes/api.live.$overlayId.session'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveOverlayIdRoute = LiveOverlayIdRouteImport.update({
  id: '/live/$overlayId',
  path: '/live/$overlayId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveOverlayIdPreviewRoute = LiveOverlayIdPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => LiveOverlayIdRoute,
} as any)
const LiveOverlayIdMetricsRoute = LiveOverlayIdMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => LiveOverlayIdRoute,
} as any)
const LiveOverlayIdMapRoute = LiveOverlayIdMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => LiveOverlayIdRoute,
} as any)
const LiveOverlayIdMetricMetricRoute =
  LiveOverlayIdMetricMetricRouteImport.update({
    id: '/metric/$metric',
    path: '/metric/$metric',
    getParentRoute: () => LiveOverlayIdRoute,
  } as any)
const ApiLiveOverlayIdSessionRoute = ApiLiveOverlayIdSessionRouteImport.update({
  id: '/api/live/$overlayId/session',
  path: '/api/live/$overlayId/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/live/$overlayId': typeof LiveOverlayIdRouteWithChildren
  '/live/$overlayId/map': typeof LiveOverlayIdMapRoute
  '/live/$overlayId/metrics': typeof LiveOverlayIdMetricsRoute
  '/live/$overlayId/preview': typeof LiveOverlayIdPreviewRoute
  '/api/live/$overlayId/session': typeof ApiLiveOverlayIdSessionRoute
  '/live/$overlayId/metric/$metric': typeof LiveOverlayIdMetricMetricRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/live/$overlayId': typeof LiveOverlayIdRouteWithChildren
  '/live/$overlayId/map': typeof LiveOverlayIdMapRoute
  '/live/$overlayId/metrics': typeof LiveOverlayIdMetricsRoute
  '/live/$overlayId/preview': typeof LiveOverlayIdPreviewRoute
  '/api/live/$overlayId/session': typeof ApiLiveOverlayIdSessionRoute
  '/live/$overlayId/metric/$metric': typeof LiveOverlayIdMetricMetricRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/live/$overlayId': typeof LiveOverlayIdRouteWithChildren
  '/live/$overlayId/map': typeof LiveOverlayIdMapRoute
  '/live/$overlayId/metrics': typeof LiveOverlayIdMetricsRoute
  '/live/$overlayId/preview': typeof LiveOverlayIdPreviewRoute
  '/api/live/$overlayId/session': typeof ApiLiveOverlayIdSessionRoute
  '/live/$overlayId/metric/$metric': typeof LiveOverlayIdMetricMetricRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/live/$overlayId'
    | '/live/$overlayId/map'
    | '/live/$overlayId/metrics'
    | '/live/$overlayId/preview'
    | '/api/live/$overlayId/session'
    | '/live/$overlayId/metric/$metric'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/live/$overlayId'
    | '/live/$overlayId/map'
    | '/live/$overlayId/metrics'
    | '/live/$overlayId/preview'
    | '/api/live/$overlayId/session'
    | '/live/$overlayId/metric/$metric'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/live/$overlayId'
    | '/live/$overlayId/map'
    | '/live/$overlayId/metrics'
    | '/live/$overlayId/preview'
    | '/api/live/$overlayId/session'
    | '/live/$overlayId/metric/$metric'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  LiveOverlayIdRoute: typeof LiveOverlayIdRouteWithChildren
  ApiLiveOverlayIdSessionRoute: typeof ApiLiveOverlayIdSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$overlayId': {
      id: '/live/$overlayId'
      path: '/live/$overlayId'
      fullPath: '/live/$overlayId'
      preLoaderRoute: typeof LiveOverlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$overlayId/preview': {
      id: '/live/$overlayId/preview'
      path: '/preview'
      fullPath: '/live/$overlayId/preview'
      preLoaderRoute: typeof LiveOverlayIdPreviewRouteImport
      parentRoute: typeof LiveOverlayIdRoute
    }
    '/live/$overlayId/metrics': {
      id: '/live/$overlayId/metrics'
      path: '/metrics'
      fullPath: '/live/$overlayId/metrics'
      preLoaderRoute: typeof LiveOverlayIdMetricsRouteImport
      parentRoute: typeof LiveOverlayIdRoute
    }
    '/live/$overlayId/map': {
      id: '/live/$overlayId/map'
      path: '/map'
      fullPath: '/live/$overlayId/map'
      preLoaderRoute: typeof LiveOverlayIdMapRouteImport
      parentRoute: typeof LiveOverlayIdRoute
    }
    '/live/$overlayId/metric/$metric': {
      id: '/live/$overlayId/metric/$metric'
      path: '/metric/$metric'
      fullPath: '/live/$overlayId/metric/$metric'
      preLoaderRoute: typeof LiveOverlayIdMetricMetricRouteImport
      parentRoute: typeof LiveOverlayIdRoute
    }
    '/api/live/$overlayId/session': {
      id: '/api/live/$overlayId/session'
      path: '/api/live/$overlayId/session'
      fullPath: '/api/live/$overlayId/session'
      preLoaderRoute: typeof ApiLiveOverlayIdSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LiveOverlayIdRouteChildren {
  LiveOverlayIdMapRoute: typeof LiveOverlayIdMapRoute
  LiveOverlayIdMetricsRoute: typeof LiveOverlayIdMetricsRoute
  LiveOverlayIdPreviewRoute: typeof LiveOverlayIdPreviewRoute
  LiveOverlayIdMetricMetricRoute: typeof LiveOverlayIdMetricMetricRoute
}

const LiveOverlayIdRouteChildren: LiveOverlayIdRouteChildren = {
  LiveOverlayIdMapRoute: LiveOverlayIdMapRoute,
  LiveOverlayIdMetricsRoute: LiveOverlayIdMetricsRoute,
  LiveOverlayIdPreviewRoute: LiveOverlayIdPreviewRoute,
  LiveOverlayIdMetricMetricRoute: LiveOverlayIdMetricMetricRoute,
}

const LiveOverlayIdRouteWithChildren = LiveOverlayIdRoute._addFileChildren(
  LiveOverlayIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  LiveOverlayIdRoute: LiveOverlayIdRouteWithChildren,
  ApiLiveOverlayIdSessionRoute: ApiLiveOverlayIdSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
